// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnilistStatus() {
  return window['go']['main']['App']['AnilistStatus']();
}

export function BindEpisode(arg1, arg2) {
  return window['go']['main']['App']['BindEpisode'](arg1, arg2);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function DetectMpv() {
  return window['go']['main']['App']['DetectMpv']();
}

export function DownloadHistory() {
  return window['go']['main']['App']['DownloadHistory']();
}

export function DownloadStatus() {
  return window['go']['main']['App']['DownloadStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportLocalFile() {
  return window['go']['main']['App']['ImportLocalFile']();
}

export function InitError() {
  return window['go']['main']['App']['InitError']();
}

export function ListAiringSchedule(arg1, arg2) {
  return window['go']['main']['App']['ListAiringSchedule'](arg1, arg2);
}

export function ListCurrentlyWatching() {
  return window['go']['main']['App']['ListCurrentlyWatching']();
}

export function ListEpisodes() {
  return window['go']['main']['App']['ListEpisodes']();
}

export function LogoutAnilist() {
  return window['go']['main']['App']['LogoutAnilist']();
}

export function OpenAnilistLogin() {
  return window['go']['main']['App']['OpenAnilistLogin']();
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function PickMpvPath() {
  return window['go']['main']['App']['PickMpvPath']();
}

export function PlayEpisode(arg1) {
  return window['go']['main']['App']['PlayEpisode'](arg1);
}

export function ResumeDownload() {
  return window['go']['main']['App']['ResumeDownload']();
}

export function SaveAnilistToken(arg1) {
  return window['go']['main']['App']['SaveAnilistToken'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function StartMagnet(arg1) {
  return window['go']['main']['App']['StartMagnet'](arg1);
}

export function StartTorrentFile() {
  return window['go']['main']['App']['StartTorrentFile']();
}
