// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {torrentx} from '../models';

export function AddRSSFeed(arg1:string,arg2:string):Promise<main.RSSFeedView>;

export function AnilistStatus():Promise<main.AnilistStatus>;

export function AppVersion():Promise<string>;

export function ApplyUpdate():Promise<void>;

export function BindEpisode(arg1:number,arg2:number):Promise<void>;

export function CancelDownload(arg1:number):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ConfirmWindowClose(arg1:string,arg2:boolean):Promise<void>;

export function CountNewRSSFeedItems():Promise<number>;

export function DetectMpv():Promise<string>;

export function DownloadHistory():Promise<Array<torrentx.JobView>>;

export function DownloadStatus():Promise<torrentx.JobView>;

export function FinishDownload(arg1:number):Promise<void>;

export function GetAnime(arg1:number):Promise<main.AnimeView>;

export function GetSettings():Promise<main.SettingsView>;

export function ImportLocalFile():Promise<main.ImportResult>;

export function InitError():Promise<string>;

export function InspectTorrent(arg1:string):Promise<torrentx.ContentsView>;

export function ListAiringSchedule(arg1:number,arg2:number):Promise<Array<main.AiringScheduleView>>;

export function ListAnimeList(arg1:string):Promise<Array<main.WatchingEntryView>>;

export function ListAnimeListCounts():Promise<Record<string, number>>;

export function ListCurrentlyWatching():Promise<Array<main.WatchingEntryView>>;

export function ListEpisodes():Promise<Array<main.EpisodeView>>;

export function ListRSSFeedItems(arg1:boolean):Promise<Array<main.RSSFeedItemView>>;

export function ListRSSFeeds():Promise<Array<main.RSSFeedView>>;

export function ListStreamingEpisodeThumbnails(arg1:number):Promise<Array<main.StreamingEpisodeThumbnailView>>;

export function LogoutAnilist():Promise<void>;

export function MarkAllRSSFeedItemsSeen():Promise<void>;

export function MarkRSSFeedItemsSeen(arg1:Array<number>):Promise<void>;

export function OpenAnilistLogin():Promise<void>;

export function OpenDownloadFolder():Promise<void>;

export function PauseDownload(arg1:number):Promise<void>;

export function PickDownloadDir():Promise<string>;

export function PickMpvPath():Promise<string>;

export function PickTorrentFile():Promise<string>;

export function PlayEpisode(arg1:number):Promise<void>;

export function PollRSSFeedsNow():Promise<void>;

export function RemoveDownload(arg1:number,arg2:boolean):Promise<void>;

export function RemoveRSSFeed(arg1:number):Promise<void>;

export function ResumeDownload(arg1:number):Promise<void>;

export function ResumeSeeding(arg1:number):Promise<void>;

export function SaveAnilistSettings(arg1:number):Promise<void>;

export function SaveAnilistToken(arg1:string):Promise<void>;

export function SaveAnimeListEntry(arg1:main.AnimeListEntryInput):Promise<void>;

export function SaveDesktopSettings(arg1:boolean):Promise<void>;

export function SaveDownloadSettings(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:boolean,arg8:boolean):Promise<void>;

export function SaveNetworkSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SavePlaybackSettings(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SaveRSSPollSettings(arg1:number):Promise<void>;

export function SaveUpdateChannel(arg1:string):Promise<void>;

export function SearchAnime(arg1:string):Promise<Array<main.AnimeView>>;

export function SearchNyaa(arg1:string):Promise<Array<main.NyaaResultView>>;

export function SearchTokyoToshokan(arg1:string):Promise<Array<main.NyaaResultView>>;

export function SetAnimeListStatus(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SetRSSFeedEnabled(arg1:number,arg2:boolean):Promise<void>;

export function StartMagnet(arg1:string):Promise<void>;

export function StartTorrent(arg1:string,arg2:Array<torrentx.FileView>):Promise<void>;

export function StartTorrentFile():Promise<void>;

export function StartTorrentURL(arg1:string):Promise<void>;

export function TestNetworkConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnbindEpisode(arg1:number):Promise<void>;
