// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnilistStatus() {
  return window['go']['main']['App']['AnilistStatus']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function BindEpisode(arg1, arg2) {
  return window['go']['main']['App']['BindEpisode'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DetectMpv() {
  return window['go']['main']['App']['DetectMpv']();
}

export function DownloadHistory() {
  return window['go']['main']['App']['DownloadHistory']();
}

export function DownloadStatus() {
  return window['go']['main']['App']['DownloadStatus']();
}

export function FinishDownload(arg1) {
  return window['go']['main']['App']['FinishDownload'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportLocalFile() {
  return window['go']['main']['App']['ImportLocalFile']();
}

export function InitError() {
  return window['go']['main']['App']['InitError']();
}

export function InspectTorrent(arg1) {
  return window['go']['main']['App']['InspectTorrent'](arg1);
}

export function ListAiringSchedule(arg1, arg2) {
  return window['go']['main']['App']['ListAiringSchedule'](arg1, arg2);
}

export function ListAnimeList(arg1) {
  return window['go']['main']['App']['ListAnimeList'](arg1);
}

export function ListCurrentlyWatching() {
  return window['go']['main']['App']['ListCurrentlyWatching']();
}

export function ListEpisodes() {
  return window['go']['main']['App']['ListEpisodes']();
}

export function LogoutAnilist() {
  return window['go']['main']['App']['LogoutAnilist']();
}

export function OpenAnilistLogin() {
  return window['go']['main']['App']['OpenAnilistLogin']();
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PickDownloadDir() {
  return window['go']['main']['App']['PickDownloadDir']();
}

export function PickMpvPath() {
  return window['go']['main']['App']['PickMpvPath']();
}

export function PickTorrentFile() {
  return window['go']['main']['App']['PickTorrentFile']();
}

export function PlayEpisode(arg1) {
  return window['go']['main']['App']['PlayEpisode'](arg1);
}

export function RemoveDownload(arg1, arg2) {
  return window['go']['main']['App']['RemoveDownload'](arg1, arg2);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function ResumeSeeding(arg1) {
  return window['go']['main']['App']['ResumeSeeding'](arg1);
}

export function SaveAnilistSettings(arg1) {
  return window['go']['main']['App']['SaveAnilistSettings'](arg1);
}

export function SaveAnilistToken(arg1) {
  return window['go']['main']['App']['SaveAnilistToken'](arg1);
}

export function SaveAnimeListEntry(arg1) {
  return window['go']['main']['App']['SaveAnimeListEntry'](arg1);
}

export function SaveDownloadSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveDownloadSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveNetworkSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNetworkSettings'](arg1, arg2, arg3);
}

export function SavePlaybackSettings(arg1, arg2) {
  return window['go']['main']['App']['SavePlaybackSettings'](arg1, arg2);
}

export function SaveUpdateChannel(arg1) {
  return window['go']['main']['App']['SaveUpdateChannel'](arg1);
}

export function SearchAnime(arg1) {
  return window['go']['main']['App']['SearchAnime'](arg1);
}

export function SearchNyaa(arg1) {
  return window['go']['main']['App']['SearchNyaa'](arg1);
}

export function SearchTokyoToshokan(arg1) {
  return window['go']['main']['App']['SearchTokyoToshokan'](arg1);
}

export function SetAnimeListStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAnimeListStatus'](arg1, arg2, arg3);
}

export function StartMagnet(arg1) {
  return window['go']['main']['App']['StartMagnet'](arg1);
}

export function StartTorrent(arg1, arg2) {
  return window['go']['main']['App']['StartTorrent'](arg1, arg2);
}

export function StartTorrentFile() {
  return window['go']['main']['App']['StartTorrentFile']();
}

export function StartTorrentURL(arg1) {
  return window['go']['main']['App']['StartTorrentURL'](arg1);
}

export function TestNetworkConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestNetworkConnection'](arg1, arg2, arg3);
}
